_target_: src.modules.single_module.MNISTLitModule

defaults:
  - _self_
  - network: mnist.yaml

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0

scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: max
    factor: 0.1
    min_lr: 1.0e-9
    patience: 10
    verbose: false
  extras:
    monitor: acc/valid
    interval: epoch
    frequency: 1

logging:
  on_step: false
  on_epoch: true
  sync_dist: false
  prog_bar: true
