model:
  _target_: src.modules.models.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 256
  lin2_size: 256
  lin3_size: 256
  output_size: 10

loss:
  _target_: torch.nn.CrossEntropyLoss

output_activation:
  _target_: torch.softmax
  dim: 1
