model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch{epoch:03d}-acc_valid{acc/valid:.4f}"
  monitor: acc/valid
  verbose: false
  save_last: true
  save_top_k: 3
  mode: max
  auto_insert_metric_name: false
  save_weights_only: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: acc/valid
  min_delta: 0.0001
  patience: 10
  verbose: false
  mode: max
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 1

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
